{% set name = "duplexanalysis" %}
{% set version = "0.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f0a98bd455b7c84f54df325caa7d94e54d8125267e19e6bf11a1c66909c030a8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - duplexanalysis

about:
  home: https://github.com/monikaheinzl/duplexanalysis
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: Tool for analysing duplex sequencing data
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
