{% set version = "0.0.1" %}

package:
  name: duplexanalysis
  version: {{ version }}
  
source:
  fn: duplexanalysis-{{ version }}.tar.gz
  url: https://pypi.org/project/duplexanalysis/duplexanalysis-{{ version }}.tar.gz
  
build:
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - python
	- setuptools

  run:
    - python

about:
  home: https://github.com/monikaheinzl/galaxyProject
  summary: "Duplex Sequencing Analysis: Tools for analysing duplex sequencing data."