categories: [Graphics]
description: Tool that plots a histogram of sizes of read families from tags that were aligned to regions of the reference genome!
long_description: Tool that plots a histogram of sizes of read families from tags that were aligned to regions of the reference genome!
name: Family size distribution of sizes of read families of aligned tags to reference genome 
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/galaxyProject/tree/master/tools/fsd_regions
