categories: [Graphics]
description: Tool that plots a histogram of sizes of read families!
long_description: Tool that plots a histogram of sizes of read families!
name: Family size distribution of sizes of read families
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/galaxyProject/tree/master/tools/fsd
