categories: [Graphics]
description: Duplex Sequencing Analysis: Tools that analyse duplex sequencing data
long_description: This package includes tools for the analysis of the read family sizes and Hamming distances of the tags.
name: duplexanalysis 
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/duplexanalysis
