categories: [Sequence Analysis]
description: Tool that extracts tags of reads that are within user-specified regions
long_description: Tool that takes a SAM file, start and stop positions as input and prints all tags of reads that overlap with regions to user specified output file.
name: range2tag
owner: gpovysil
remote_repository_url: https://github.com/gpovysil/galaxy/tools/range2tag
