{% set version = "0.0.1" %}

package:
  name: duplexAnalysis
  version: {{ version }}

build:
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - make
    - gcc
    - python
    - wget

  run:
    - libgcc
    - python
    - paste
    - gawk

about:
  home: https://github.com/monikaheinzl/galaxyProject
  license: GPLv2
  license_file: LICENSE.txt
  summary: "Duplex Sequencing Analysis: Tools for analysing duplex sequencing data."