{% set version = "0.0.1" %}

package:
  name: duplexanalysis
  version: {{ version }}
  
source:
  fn: duplexanalysis-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/duplexanalysis/duplexanalysis-{{ version }}.tar.gz
  sha256: f0a98bd455b7c84f54df325caa7d94e54d8125267e19e6bf11a1c66909c030a8
  
build:
  number: 0
  skip: True  # [not py27]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/monikaheinzl/galaxyProject
  summary: "Duplex Sequencing Analysis: Tools for analysing duplex sequencing data."