categories: [Graphics]
description: Tool that plots a histogram of sizes of read families from various stages of the dunovo pipeline!
long_description: Tool that plots a histogram of sizes of read families from various stages of the dunovo pipeline!
name: Family size distribution of sizes of read families from various stages of data analysis 
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/galaxyProject/tree/master/tools/fsd_beforevsafter
