categories: [Graphics]
description: Tool that plots a histogram of sizes of read families
long_description: Tool that plots a histogram of sizes of read families
name: fsd
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/duplexanalysis_galaxy/tree/master/tools/fsd
