categories: [Graphics]
description: Tool that plots a histogram of sizes of read families that were aligned to regions of the reference genome
long_description: Tool that plots a histogram of sizes of read families that were aligned to regions of the reference genome
name: fsd_regions
owner: mheinzl
remote_repository_url: https://github.com/monikaheinzl/duplexanalysis_galaxy/tree/master/tools/fsd_regions
